name: "Go"

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3

    - name: Run Tests
      run: go test -timeout 30m ./...

    - name: Run Benchmarks
      run: go test -timeout 30m -v -run ^$ -bench . -benchmem ./...
