name: "Go"

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: Run Tests
      run: go test -timeout 20m -v

    - name: Run Benchmarks
      run: go test -timeout 20m -v -run ^$ -bench . -benchmem
