name: "Golang"

on:
  push:
    branches: [ main, dev ]

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: Run Tests
      run: go test -timeout 20m -v

    - name: Run Benchmarks
      run: go test -timeout 20m -run ^$ -bench . -benchmem
