# Copyright (c) 2023, Serhat Şevki Dinçer.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: QA

on:
  push:
    branches: [ main, dev ]
permissions:
  contents: read
env:
  GOAMD64: v2

jobs:
  Tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        go: [ '1.19', '1.20' ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Run Tests
      run: go test -timeout 1h -v

  Analysis:
    permissions:
      actions: read
      security-events: write
    strategy:
      matrix:
        go: [ '1.19', '1.20' ]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Initialize
      uses: github/codeql-action/init@v2
      with:
        languages: go
    - name: Analyze
      uses: github/codeql-action/analyze@v2
